# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  selector:
    app: todo-app-denx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000
  type: LoadBalancer
